name: Dart CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    container:
      image:  google/dart:latest

    steps:
    - uses: actions/checkout@v2
    - name: Check Lints (dartanalyzer)
      run: dartanalyzer lib
    - name: flutter-cli
      uses: steebchen/flutter@v1.1.0
